# Generated by Django 5.2 on 2025-05-09 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
    ]
